Repository beclab/Installer, pull requests merged in 2024-12, with the labels that each got.

#68 feat: detect public ip and adjust the setting of "selfhosted"
  .goreleaser.yaml
  pkg/common/kube_runtime.go
  pkg/core/util/ip.go
  pkg/core/util/util.go
  pkg/phase/cluster/changeip.go
  pkg/terminus/prepares.go
  pkg/terminus/settings.go
  pkg/terminus/tasks.go
  pkg/terminus/welcome.go
Labels: feat

#70 fix: install sudo if it's missing
  pkg/common/loader.go
Labels: fix

#74 feat: add .DS_Store in .gitingore
  .gitignore
Labels: feat

#75 fix: ensure no containerd already exists before preparing
  pkg/bootstrap/precheck/module.go
  pkg/bootstrap/precheck/tasks.go
  pkg/terminus/account.go
Labels: fix

#78 ci: use stable runner ubuntu-22.04 rather than latest
  .github/workflows/release.yaml
Labels: ci

#76 fix: ignore the value of Windows gpu env vars during wsl installation
  pkg/phase/cluster/linux.go
  pkg/windows/tasks.go
Labels: fix

#77 feat: support installing Olares in PVE LXC containers
  pkg/bootstrap/os/module.go
  pkg/bootstrap/os/prepares.go
  pkg/bootstrap/os/tasks.go
  pkg/bootstrap/os/templates/init_lxc.go
  pkg/bootstrap/patch/tasks.go
  pkg/common/common.go
  pkg/core/common/common.go
  pkg/core/connector/system.go
  pkg/kubernetes/tasks.go
  pkg/kubernetes/templates/v1beta2/kubeadm_config.go
  pkg/phase/system/linux.go
Labels: feat

#81 fix: check the status of apt-get update for PVE
  pkg/bootstrap/precheck/module.go
  pkg/bootstrap/precheck/tasks.go
Labels: fix

#80 fix: add precheck for port 9100
  pkg/bootstrap/precheck/tasks.go
Labels: fix

#83 feat: support setting registry mirrors for minikube
  go.mod
  go.sum
  pkg/common/common.go
  pkg/kubesphere/minikube.go
  pkg/phase/system/macos.go
Labels: feat

#84 fix: get cuda version
  pkg/gpu/module.go
  pkg/gpu/tasks.go
  pkg/phase/cluster/linux.go
  pkg/terminus/ossystem.go
Labels: fix

#85 feat: seperate phase & command for storage installation
  cmd/ctl/options/cli_options.go
  cmd/ctl/os/install.go
  cmd/ctl/os/storage.go
  pkg/common/common.go
  pkg/common/kube_runtime.go
  pkg/phase/cluster/delete_cluster.go
  pkg/phase/cluster/linux.go
  pkg/phase/cluster/utils.go
  pkg/phase/system/linux.go
  pkg/phase/system/storage.go
  pkg/phase/system/utils.go
  pkg/pipelines/install_terminus.go
  pkg/pipelines/prepare_system.go
  pkg/pipelines/storage.go
  pkg/storage/juicefs.go
  pkg/storage/module.go
  pkg/storage/tasks.go
  pkg/storage/validate.go
Labels: feat

#86 fix: reset config path of cri plugin in minikube
  pkg/kubesphere/minikube.go
Labels: fix

#87 fix: tag k8s images in minikube to avoid destructive reload
  pkg/kubesphere/minikube.go
Labels: fix

#88 feat: add separate command for precheck
  cmd/ctl/options/cli_options.go
  cmd/ctl/os/precheck.go
  cmd/ctl/os/root.go
  pkg/bootstrap/os/module.go
  pkg/bootstrap/os/tasks.go
  pkg/bootstrap/patch/module.go
  pkg/bootstrap/patch/tasks.go
  pkg/bootstrap/precheck/module.go
  pkg/bootstrap/precheck/tasks.go
  pkg/core/connector/system.go
  pkg/phase/system/linux.go
  pkg/phase/system/wsl.go
  pkg/pipelines/precheck.go
Labels: feat

#89 feat: add windows firewall rule
  pkg/common/common.go
  pkg/windows/modules.go
  pkg/windows/tasks.go
Labels: feat
